config/routes.rb
Bloccit::Application.routes.draw do
  
  devise_for :users
  resources :users, only: [:update, :show, :index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end
  
  resources :posts, only: [:index] do 
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :value, inclusion: { in: [-1,1], message: "%{value} is not a valid vote."}

  after_save :update_post

  def up_vote?
    post.up_vote!
  end

  def down_vote?
    post.down_vote!
  end

  private

  def update_post
    post.update_rank
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_filter :authenticate_user!

  before_action :load_post_and_vote

  def up_vote
    if @post.already_up_voted_by_user?(current_user)
      flash[:error] = "You already upvoted the post."
      redirect_to :back
    elsif @post.already_down_voted_by_user?(current_user)
      @post.remove_down_vote!(current_user)
      @post.up_vote!(current_user)
      redirect_to :back
    else
      @post.up_vote!(current_user)
      redirect_to :back
    end
  end

  def down_vote
    if @post.already_down_voted_by_user?(current_user)
      flash[:error] = "You already downvoted the post."
      redirect_to :back
    elsif @post.already_up_voted_by_user?(current_user)
      @post.remove_up_vote!(current_user)
      @post.down_vote!(current_user)
      redirect_to :back
    else
      @post.down_vote!(current_user)
      redirect_to :back
    end
  end

  private

    def load_post_and_vote
      @post = Post.find(params[:post_id])
      @topic = @post.topic
    end

end

app/views/votes/_voter.html.erb
<% if policy(Vote.new).create? %>
  <div class="pull-left vote-arrows">
    <div>
      <%= link_to "", 
        post_up_vote_path(post), 
        class: "glyphicon glyphicon-chevron-up #{(post.already_up_voted_by_user?(current_user)) ? 'voted' : ''} ", method: post%></div>
    <div><strong><%= post.points %></strong></div>
    <div><%= link_to "", post_down_vote_path(post), 
    class: "glyphicon glyphicon-chevron-down #{(post.already_down_voted_by_user?(current_user))  ? 'voted' : ''}", method: post%></div>
  </div>
<% end %>